name: Build and Publish

on:
  push:
    branches:
      - devel
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up compiler on Linux
        if: runner.os == 'Linux'
        run: sudo apt-get install -y gcc

      - name: Set up compiler on Windows
        if: runner.os == 'Windows'
        run: choco install mingw

      - name: Set up compiler on macOS
        if: runner.os == 'macOS'
        run: brew install gcc

      - name: Build
        run: make

      - name: Archive build artifacts
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: Ne2x-${{ matrix.os }}
          path: Ne2x

      - name: Publish
        if: github.ref == 'refs/heads/master'
        run: |
          mkdir -p release
          cp Ne2x release/
          # Aggiungere qui il comando per pubblicare i binari, ad esempio usando GitHub Releases
          # Esempio: gh release create v1.0.0 release/Ne2x --title "Release v1.0.0" --notes "First release"
